In [1]:
pip install tensorboard

   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/5.5 MB ? eta -:--:--
   --- ------------------------------------ 0.5/5.5 MB 1.4 MB/s eta 0:00:04
   ------- -------------------------------- 1.0/5.5 MB 1.6 MB/s eta 0:00:03
   ----------- ---------------------------- 1.6/5.5 MB 1.7 MB/s eta 0:00:03
   ------------- -------------------------- 1.8/5.5 MB 1.8 MB/s eta 0:00:03
   --------------- ------------------------ 2.1/5.5 MB 1.8 MB/s eta 0:00:02
   --------------- ------------------------ 2.1/5.5 MB 1.8 MB/s eta 0:00:02
   --------------- ------------------------ 2.1/5.5 MB 1.8 MB/s eta 0:00:02
   ----------------- ---------------------- 2.4/5.5 MB

In [11]:
from tool import create_graph
from tool import add_feature_to_graph_edges
triples = [(1,2,3),(4,2,1),(5,1,3),(4,3,2),(3,2,1)]
graph  = create_graph(triples)
# add_feature_to_graph_edges(graph,triples,3)



ImportError: cannot import name 'add_feature_to_graph_edges' from 'tool' (e:\phd\semester-4\codes\deep-conseption\tool.py)

In [1]:
import torch.nn as nn
import torch
rel_head_emb = nn.Parameter(torch.Tensor(14, 32))
nn.init.xavier_normal_(rel_head_emb, gain=nn.init.calculate_gain('relu'))
# nn.init.xavier_normal_(self.rel_tail_emb, gain=nn.init.calculate_gain('relu'))
rel_head_emb

Parameter containing:
tensor([[ 1.5214e-01,  1.5381e-01,  2.7228e-01, -1.5122e-01, -5.6702e-01,
          1.6938e-01, -4.4793e-01,  5.7519e-01, -1.0396e-01,  2.8053e-01,
         -8.1923e-02,  2.1488e-01, -2.4865e-01,  2.5526e-01, -3.4141e-01,
         -1.8834e-02, -3.6438e-01, -9.5129e-02,  2.9865e-01,  2.6161e-01,
         -2.1928e-01, -6.1039e-01, -2.3403e-01, -1.0242e-01, -3.8337e-01,
         -3.1318e-03, -1.2141e-01,  8.1265e-01,  8.4908e-03,  8.2591e-01,
         -1.6630e-01,  1.9296e-01],
        [ 1.6849e-01,  4.0864e-01, -1.2689e-01,  6.3680e-02,  6.7698e-01,
          3.8007e-01, -4.8723e-01,  8.1648e-02,  9.1819e-02, -2.5537e-01,
         -4.1228e-02, -4.4854e-01,  9.4075e-02, -2.7943e-01, -2.3268e-01,
         -7.2894e-02,  3.4977e-01,  1.3668e-01, -2.8490e-01,  5.9107e-02,
         -1.2490e-01,  3.4581e-01, -2.7372e-01, -1.4857e-01,  5.0403e-01,
         -3.8007e-01,  2.8534e-01, -3.2034e-01,  3.7444e-01,  2.0880e-01,
         -1.0105e-01,  2.4907e-01],
        [ 1.7699e-

In [12]:
x = torch.tensor([1, 2, 3])
print(x.shape)
x_s0=x.unsqueeze(0)
print(x_s0.shape)
x_s1=x.unsqueeze(1)
print(x_s1.shape)
x = torch.tensor([[[1], [2], [3]]])  # Shape: (1, 3, 1)
print(x)
print(x.squeeze())




torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])
tensor([[[1],
         [2],
         [3]]])
tensor([1, 2, 3])
